Global:
  algorithm: SRN
  use_gpu: true
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: output/rec_pvam_withrotate
  save_epoch_step: 1
  eval_batch_step: 8000
  train_batch_size_per_card: 64
  test_batch_size_per_card: 1
  image_shape: [1, 64, 256]
  max_text_length: 25
  character_type: en
  loss_type: srn
  num_heads: 8
  average_window: 0.15
  max_average_window: 15625
  min_average_window: 10000
  reader_yml: ./configs/rec/rec_benchmark_reader.yml
  pretrain_weights: 
  checkpoints:
  save_inference_dir:
  infer_img:

Architecture:
  function: ppocr.modeling.architectures.rec_model,RecModel

Backbone:
  function: ppocr.modeling.backbones.rec_resnet50_fpn,ResNet
  layers: 50
 
Head:
  function: ppocr.modeling.heads.rec_srn_all_head,SRNPredict
  encoder_type: rnn
  num_encoder_TUs: 2
  num_decoder_TUs: 4
  hidden_dims: 512
  SeqRNN:
    hidden_size: 256
    
Loss:
  function: ppocr.modeling.losses.rec_srn_loss,SRNLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.0001
  beta1: 0.9
  beta2: 0.999
