Global:
  use_gpu: false
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/mv3_none_none_ctc/
  save_epoch_step: 500
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: 2000
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  load_static_weights: True
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: True
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  max_text_length: 25
  character_dict_path:
  character_type: 'en'
  use_space_char: False
  infer_mode: False
  use_tps: False


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  learning_rate:
    lr: 0.0005
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    small_stride: [ 1, 2, 2, 2 ]
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTC
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

TRAIN:
  dataset:
    name: LMDBDateSet
    file_list:
      - ./rec/train # dataset1
    ratio_list: [ 0.4,0.6 ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecAug:
      - RecResizeImg:
          image_shape: [ 3,32,100 ]
      - keepKeys:
          keep_keys: [ 'image','label','length' ] # dataloader will return list in this order
  loader:
    batch_size: 256
    shuffle: True
    drop_last: True
    num_workers: 8

EVAL:
  dataset:
    name: LMDBDateSet
    file_list:
      - ./rec/val/
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [ 3,32,100 ]
      - keepKeys:
          keep_keys: [ 'image','label','length' ] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size: 256
    num_workers: 8
