Global:
  algorithm: EAST
  use_gpu: true
  epoch_num: 100000
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/det_east/
  save_epoch_step: 200
  eval_batch_step: 5000
  train_batch_size_per_card: 16
  test_batch_size_per_card: 16
  image_shape: [3, 512, 512]
  reader_yml: ./configs/det/det_east_icdar15_reader.yml
  pretrain_weights: ./pretrain_models/MobileNetV3_pretrained/MobileNetV3_large_x0_5_pretrained/
  checkpoints:
  save_res_path: ./output/det_east/predicts_east.txt
  save_inference_dir:
  
Architecture:
  function: ppocr.modeling.architectures.det_model,DetModel

Backbone:
  function: ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3
  scale: 0.5
  model_name: large

Head:
  function: ppocr.modeling.heads.det_east_head,EASTHead
  model_name: small
  
Loss:
  function: ppocr.modeling.losses.det_east_loss,EASTLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.001
  beta1: 0.9
  beta2: 0.999

PostProcess:
  function: ppocr.postprocess.east_postprocess,EASTPostPocess
  score_thresh: 0.8
  cover_thresh: 0.1
  nms_thresh: 0.2
  