TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.east_process,EASTProcessTrain
  num_workers: 8
  img_set_dir: ./train_data/icdar2015/text_localization/
  label_file_path: ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
  background_ratio: 0.125
  min_crop_side_ratio: 0.1
  min_text_size: 10

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.east_process,EASTProcessTest
  img_set_dir: ./train_data/icdar2015/text_localization/
  label_file_path: ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.east_process,EASTProcessTest
  infer_img:
  img_set_dir: ./train_data/icdar2015/text_localization/
  label_file_path: ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
  do_eval: True
