blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Q&A
    url: https://github.com/PaddlePaddle/PaddleOCR/discussions/categories/q-a
    about: Ask the community for help
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/PaddlePaddle/PaddleOCR/discussions/categories/ideas
    about: Share ideas for new features
  - name: ğŸ™Œ Show and tell
    url: https://github.com/PaddlePaddle/PaddleOCR/discussions/categories/show-and-tell
    about: Show off something you've made
