Global:
  algorithm: CRNN
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_german
  save_epoch_step: 1
  eval_batch_step: 2000
  train_batch_size_per_card: 256
  test_batch_size_per_card: 256
  image_shape: [3, 32, 320]
  max_text_length: 25
  character_type: german
  character_dict_path: ./ppocr/utils/dict/german_dict.txt
  loss_type: ctc
  distort: true
  use_space_char: false
  reader_yml: ./configs/rec/multi_languages/rec_ger_reader.yml
  pretrain_weights:
  checkpoints:
  save_inference_dir:
  infer_img:

Architecture:
  function: ppocr.modeling.architectures.rec_model,RecModel

Backbone:
  function: ppocr.modeling.backbones.rec_mobilenet_v3,MobileNetV3
  scale: 0.5
  model_name: small
  small_stride: [1, 2, 2, 2]

Head:
  function: ppocr.modeling.heads.rec_ctc_head,CTCPredict
  encoder_type: rnn
  SeqRNN:
    hidden_size: 48
    
Loss:
  function: ppocr.modeling.losses.rec_ctc_loss,CTCLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  l2_decay: 0.00001
  base_lr: 0.001
  beta1: 0.9
  beta2: 0.999
  decay:
    function: cosine_decay
    step_each_epoch: 254
    total_epoch: 500
